Fixing camera search bar
UNLV-CS472-672/2024-F-GROUP1-Tabby pull request #26
Opened 2024-10-31 07:24 UTC by caesarx26

# Pull Request Template

## Description
I fixed bugs with the search bar to have it show correctly and be hidden when categories are selected. 

I also fixed the camera modal to show up when a button is pressed in the footer. And in the modal a function is passed into it to set the state to close the modal when the cancel button is pressed or the user clicks anywhere outside the modal. 

The modal buttons to take a picture and get a picture are disabled when first pressed and then enabled when they are done doing the request or if the person cancels the request to take a picture or get a picture. This is to prevent the user clicking a button more than one at a time so no multiple pops up to get a picture occur. 

## Type of Change

- [ x] Bugfix
- [ ] New Feature
- [ ] Documentation Update
- [ ] Other (please describe):

## Checklist

- [ x] I have read the contributing guidelines.
- [ ] I have followed the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation (if applicable).
- [x ] My changes do not generate new warnings.

## Related Issue

## Additional Notes
- the issue with jest and lint are still there from trying to add tests from a earlier pull request 
- the search bar shows up and mostly works now but it will sometimes show additional items than the ones searched for on all pages like typing "b" pulls up 1 book even tho none of the books have the letter b in it.
- I will make an issue to fix the actual filtering done in the search this pull request is to make the search bar actually show up and be hidden when it should be

2024-10-31 20:15 UTC, MrSnoodle01 commented
Overall looks good and am happy that the lint issues are fixed. 

But one thing I am curious about is why we got rid of the blur behind the camera. I thought that the blur looked nice and put the focus onto the camera pop up. 

Also it would be nice if you could make an issue for the search bar not working properly.

2024-11-04 20:33 UTC, LilAttacker requested changes
Excellent that this fixes the jest issue. I hope a few things can be addressed before merging though.

First, I'm in agreement with Josh. Not sure what happened to the blur when you tapped the camera button, but I think that was a good feature and should be kept.

Second, please explain why most of the comments for Tabby/app/library/index.tsx were removed and not replaced. I don't feel that was a necessary change, but if there's an explanation then I'll hear it.

Third, please check my other comment reviews. I don't care much if they aren't implemented, but please at least address them.

--

I will also say, I think both Tabby/components/FooterNavBar.tsx and Tabby/components/camera/CameraModel.tsx could use some more documentation. Whether added or not won't change my review, but I think it'll be a good thing for the project if it was included.

2024-11-04 20:33 UTC, LilAttacker commented on Tabby/components/FooterNavBar.tsx
> +  const [isCameraModalVisible, setCameraModalVisible] = useState(false);
> set to true to show camera modal

I feel like this code is doing the opposite of what the comment says. Can this be checked?

2024-11-04 20:33 UTC, LilAttacker commented on Tabby/app/recommendations/index.tsx
> +        title: 'To Kill',
I get what you're doing here, changing the names so the search bar can be more properly tested.

But I feel keeping the names this similar may be hurting that. I think the changes should be more substantial and you can just different book names.

Some examples could be:
- Lord of the Rings
- Game of Thrones
- Twilight
- The Bible

Just take a look at these series: https://www.forbes.com/sites/entertainment/article/best-book-series/
If  you want more exact book names: https://www.barnesandnoble.com/b/books/_/N-1fZ29Z8q8

The only thing that really needs to change is the title. The description and author can stay the same unless you plan to add a filter for the author or make it to where you can search by author.

2024-11-04 20:33 UTC, LilAttacker commented on Tabby/app/recommendations/[book].tsx
> +    console.log(book, "is reccomended");
> reccomended

This is a type. It is typed recommend.

2024-11-04 20:33 UTC, LilAttacker commented on Tabby/app/recommendations/[book].tsx
> +    console.log(book, "is reccomended");
This also seems to be an issue in many places.

2024-11-04 21:30 UTC, David1000734 approved these changes
Glad we were able to get the lint issue fixed. The comment out code in the test can be removed to clean up the file a little more.

2024-11-04 21:56 UTC, MrSnoodle01 approved these changes

2024-11-04 22:18 UTC, merged