Favorites tab
UNLV-CS472-672/2024-F-GROUP1-Tabby pull request #43
Opened 2024-11-07 03:30 UTC by MrSnoodle01

## Description
Added the favorites page, although it is currently only using temporary values since we do not have any sort of database yet. 

## Type of Change

- [ ] Bugfix
- [x] New Feature
- [ ] Documentation Update
- [ ] Other (please describe):

## Checklist

- [x] I have read the contributing guidelines.
- [x] I have followed the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation (if applicable).
- [x] My changes do not generate new warnings.

## Additional Notes

2024-11-07 22:00 UTC, LilAttacker requested changes
This looks good, but I do have some questions.

- First, are there no tests for this? We really need to make sure those are implemented with the features we add. I'm pretty sure we only have a single frontend test currently.
- Could you add a screenshot? This seems to have modified some of what the user is expected to use and having a visual aide would help in judging it.
- Could you add some more documentation? For example, initialBooks in favorites looks like a temporary array, so adding a comment there saying its temporary could be helpful so others know not to build on it. Etc. Etc.

2024-11-07 22:02 UTC, LilAttacker commented
As an aside, you should make an issue for this and link this PR to it.

2024-11-08 16:38 UTC, MrSnoodle01 commented on Tabby/components/CameraButton.tsx
>  import { Image } from "expo-image"
I have gone ahead and removed this file entirely. This is because we now have a different file for the screen when you click on the camera button

2024-11-09 01:38 UTC, David1000734 approved these changes
Changes look good. Only thing I have to mention is that I noticed you had to change the SVG to change the color. Would it take a significant amount of time to make it so that you can pass RGB into the SVG from the tsx file so that we have more control over the color of our icons?

A minor change for a nice to have feature that is not important to have integrated into the project now.

2024-11-12 05:45 UTC, LilAttacker commented
Have you added tests to this? If you have, I'm willing to approve it.

2024-11-15 23:48 UTC, LilAttacker commented on Tabby/app/__tests__/Favorite_Test.js
> +import Favorites from '@/app/favorites';
Whole bunch of Github Warnings here

2024-11-15 23:49 UTC, LilAttacker commented on Tabby/components/camera/CameraModel.tsx
> +            const resultBase64 = result.assets[0].base64; // base64 string to send to backend
Couple of more warning here.

2024-11-16 00:01 UTC, LilAttacker requested changes
I just want to say, I see you've added a feature in Github Actions that looks to show test coverage. I think this is extremely helpful and very useful. That being said, it does show we only have about ~12% coverage for frontend.

I see you've also added tests and I think they look good so far. Unfortunately, it does look like coverage could be expanded a bit more for favorites.tsx (and just in general).

![image](https://github.com/user-attachments/assets/8857c496-a807-416e-81ac-fb4fa3127e87)

Still, very good progress. Good job!

EDIT: Thank you for fixing those warning so quickly!

2024-11-16 00:03 UTC, MrSnoodle01 commented
I have marked this pull request as a draft until I complete an adequate amount of tests for the favorites page.

2024-11-17 19:51 UTC, LilAttacker approved these changes
Congrats on adding Tests. It looks good. Coverage is good. Approved.

I just wish our coverage in the backend was better, but that's not necessarily the scope of this PR.

2024-11-18 04:33 UTC, merged